### ISSUE TITLE
[website] [Firefox] Scrolling inside the demo also scrolls the whole website

### ISSUE THREAD

**Issue by unaaagy** [nomanr/lumo-ui#32]
In Firefox, scrolling the demo also scrolls the website.

https://github.com/user-attachments/assets/a96994e5-164a-4a61-88b9-8520ec470c05

**Comment by nomanr** [comment]
Thanks for reporting the issue. It worked just fine with mouse wheel, but had a glitch when scrolling on Mac touchpad. I fixed that. Can you try and see if it works fine now?

**Comment by unaaagy** [comment]
Its still the same for me using 2 finger scroll. Mouse had no problem for me too.

I'm using Fedora 41 gnome if its relevant.

**Comment by nomanr** [comment]
got it, I'll look into it in detail then, thank you!
